spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:blogdb
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 1000
          open-in-view: false
  profiles:
    include: >
      kakao,
      naver,
      popular

logging:
  level:
    org.springframework.jdbc.core: trace
    org.hibernate.SQL: debug

resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 5 # 최대 재시도 수
        waitDuration: 5000  # 재시도 사이에 고정된 시간 [ms]
    instances:
      circuit-test:
        baseConfig: default
  circuitbreaker:
    configs:
      default:  # 기본 config 명
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10  # 최소한 호출을 10번을 기록해야 실패 비율을 계산할 수 있다.
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10s  # 서킷의 상태가 Open 에서 Half-open 으로 변경되기전에 Circuit Break가 기다리는 시간 [s]
    instances:
      circuit-test:
        baseConfig: default

